### Get SameVariants from dbSNP
# Cut out the rows that had no match in dbSNP
# Cut out the column generated by bior_vcf_to_json since it is no longer needed
cat example.vcf \
| bior_vcf_to_tjson \
| bior_same_variant --log -d $BIOR_CATALOG/dbSNP/137/00-All_GRCh37.tsv.bgz \
| grep -v "{}" \
| cut --complement -f 9 \
> out2.tsv
